Repository donsonioc2010/picasso, pull requests merged in 2023-09, with the labels that each got.

#2 docs : README수정
  Docs/Architecture.png
  README.md
Labels: documentation

#11 chore : JpaRepository Method Call할 수 있도록 과정수정 및 테스트 샘플 추가
  Api/src/main/java/picasso/server/api/Application.java
  Api/src/main/java/picasso/server/api/TestService.java
  Domain/build.gradle
  Domain/src/main/java/picasso/server/domain/domains/test/Test.java
  Domain/src/main/java/picasso/server/domain/domains/test/TestRepository.java
Labels: bug, enhancement

#9 공통기능 개발 구현
  .github/workflows/DBDOCS_BUILD.yml
  Api/src/main/java/picasso/server/api/HomeController.java
  Api/src/main/java/picasso/server/api/config/advice/GlobalControllerExceptionHandler.java
  Api/src/main/java/picasso/server/api/config/advice/GlobalRestControllerExceptionHandler.java
  Api/src/main/java/picasso/server/api/config/controller/HealthController.java
  Api/src/main/java/picasso/server/api/test/TestMessage.java
  Api/src/main/resources/static/css/style.css
  Api/src/main/resources/templates/fragment/config.html
  Api/src/main/resources/templates/fragment/footer.html
  Common/src/main/java/picasso/server/common/.keep
  Common/src/main/java/picasso/server/common/config/ConfigurationPropertiesConfig.java
  Common/src/main/java/picasso/server/common/dto/ErrorDetail.java
  Common/src/main/java/picasso/server/common/exception/BaseErrorCode.java
  Common/src/main/java/picasso/server/common/exception/BaseException.java
  Common/src/main/java/picasso/server/common/exception/ExampleException.java
  Common/src/main/java/picasso/server/common/exception/GlobalException.java
  Docs/Picasso.dbml
  README.md
Labels: documentation, enhancement

#17 ci/cd 파이프라인 구성 4트
  .github/workflows/deploy.yml
Labels: bug

#18 cicd 파이프라인 구성 4.5트
  .github/workflows/deploy.yml
Labels: bug

#25 ci/cd 파이프라인 구축 5트
  .github/workflows/deploy.yml
Labels: enhancement

#26 [feat] 파일업로드 기능 구현 (공통기능)
  Api/src/main/java/picasso/server/api/HomeController.java
  Api/src/main/java/picasso/server/api/naver_test/NaverController.java
  Api/src/main/resources/application.yml
  Api/src/main/resources/templates/test/upload-form.html
  Common/build.gradle
  Common/src/main/java/picasso/server/common/config/ConfigurationPropertiesConfig.java
  Common/src/main/java/picasso/server/common/config/NaverObjectStorageConfig.java
  Common/src/main/java/picasso/server/common/exception/FileDeleteException.java
  Common/src/main/java/picasso/server/common/exception/FileIOException.java
  Common/src/main/java/picasso/server/common/exception/FileUploadException.java
  Common/src/main/java/picasso/server/common/exception/GlobalException.java
  Common/src/main/java/picasso/server/common/properties/NaverObjectStorageProperties.java
  Common/src/main/java/picasso/server/common/util/NaverObjectStorageUsageType.java
  Common/src/main/java/picasso/server/common/util/NaverObjectStorageUtil.java
  Common/src/main/resources/application-common.yml
  Domain/src/main/resources/data.sql
Labels: enhancement

#31 [feat] Schedular Sample
  Api/src/main/java/picasso/server/api/Application.java
  Api/src/main/java/picasso/server/api/auction/scheduler/EndAuctionScheduler.java
  Api/src/main/java/picasso/server/api/auction/scheduler/StartAuctionScheduler.java
  Api/src/main/resources/templates/fragment/config.html
  Common/src/main/java/picasso/server/common/util/DateStaticConstants.java
Labels: enhancement

#30 [FEATURE] 결제 정보 dbml 수정
  Api/src/main/java/picasso/server/api/HomeController.java
  Api/src/main/java/picasso/server/payment/PGName.java
  Api/src/main/resources/static/js/.keep
  Api/src/main/resources/static/js/pay_modal.js
  Api/src/main/resources/static/js/payment.js
  Api/src/main/resources/templates/fragment/config.html
  Api/src/main/resources/templates/payment.html
  Docs/Picasso.dbml
Labels: documentation, enhancement

#37 feat : index, 메인페이지 초안
  Api/src/main/resources/static/asset/.keep
  Api/src/main/resources/static/asset/logo.png
  Api/src/main/resources/static/css/index.css
  Api/src/main/resources/static/css/style.css
  Api/src/main/resources/templates/fragment/config.html
  Api/src/main/resources/templates/fragment/header.html
  Api/src/main/resources/templates/index.html
  Api/src/main/resources/templates/layout/layout.html
Labels: enhancement

#38 refactor, feat : 컬럼 추가, 타입변경 및 rename 에 따른 기능 수정
  Api/src/main/java/picasso/server/api/auction/controller/PictureController.java
  Api/src/main/java/picasso/server/api/auction/service/PictureService.java
  Common/src/main/java/picasso/server/common/util/NaverObjectStorageUtil.java
  Domain/src/main/java/picasso/server/domain/domains/dto/PictureDTO.java
  Domain/src/main/java/picasso/server/domain/domains/items/Picture.java
  Domain/src/main/java/picasso/server/domain/domains/repository/PictureRepository.java
  Domain/src/main/resources/data.sql
Labels: enhancement

#39 결제 API 초안 작성
  Api/build.gradle
  Api/src/main/java/picasso/server/api/exchange/controller/ExchangeController.java
  Api/src/main/java/picasso/server/api/exchange/model/dto/ExchangeDTO.java
  Api/src/main/java/picasso/server/api/exchange/model/request/PostCreateExchangeRequest.java
  Api/src/main/java/picasso/server/api/exchange/service/ExchangeService.java
  Api/src/main/java/picasso/server/api/exchange/util/ExchangeUtils.java
  Api/src/main/java/picasso/server/api/exchange/validator/ExchangeValidator.java
  Api/src/main/resources/static/js/exchange.js
  Api/src/main/resources/templates/exchange.html
  Common/src/main/java/picasso/server/common/annotation/Validator.java
  Docs/Picasso.dbml
  Domain/src/main/java/picasso/server/domain/domains/items/PGName.java
  Domain/src/main/java/picasso/server/domain/domains/items/PayMethod.java
  Domain/src/main/java/picasso/server/domain/domains/items/PaymentHistory.java
  Domain/src/main/java/picasso/server/domain/domains/repository/ExchangeRepository.java
Labels: enhancement

#40 [FEATURE] 결제 API 작성
  Api/src/main/java/picasso/server/api/HomeController.java
  Api/src/main/java/picasso/server/payment/PGName.java
  Api/src/main/resources/static/js/exchange.js
  Api/src/main/resources/static/js/pay_modal.js
  Api/src/main/resources/static/js/payment.js
  Api/src/main/resources/templates/exchange.html
  Api/src/main/resources/templates/payment.html
Labels: enhancement

#46 [FEATURE] 회원가입 & 로그인 구현
  Api/src/main/java/picasso/server/api/member/controller/AuthController.java
  Api/src/main/java/picasso/server/api/member/service/UserService.java
  Api/src/main/java/picasso/server/api/user/controller/AuthController.java
  Api/src/main/java/picasso/server/api/user/controller/LoginController.java
  Api/src/main/java/picasso/server/api/user/controller/MemberController.java
  Api/src/main/java/picasso/server/api/user/controller/UserController.java
  Api/src/main/java/picasso/server/api/user/service/AuthService.java
  Api/src/main/java/picasso/server/api/user/service/AuthServiceImpl.java
  Api/src/main/java/picasso/server/api/user/service/DefaultMemberService.java
  Api/src/main/java/picasso/server/api/user/service/UserService.java
  Api/src/main/resources/templates/auth/form.html
  Api/src/main/resources/templates/auth/index.html
  Api/src/main/resources/templates/fragment/header.html
  Api/src/main/resources/templates/login/form.html
  Api/src/main/resources/templates/member/detail.html
  Api/src/main/resources/templates/member/form.html
  Api/src/main/resources/templates/member/list.html
  Api/src/main/resources/templates/user/form.html
  Domain/src/main/java/picasso/server/domain/domains/dto/UserDTO.java
  Domain/src/main/java/picasso/server/domain/domains/member/repository/UserRepository.java
  Domain/src/main/java/picasso/server/domain/domains/member/type/UserRole.java
  Domain/src/main/java/picasso/server/domain/domains/repository/UserRepository.java
  Domain/src/main/java/picasso/server/domain/domains/user/entity/Token.java
  Domain/src/main/java/picasso/server/domain/domains/user/entity/User.java
  Domain/src/main/java/picasso/server/domain/domains/user/type/LoginType.java
  Domain/src/main/java/picasso/server/domain/domains/user/type/UserRole.java
  Domain/src/main/java/picasso/server/domain/domains/user/type/UserStatus.java
Labels: enhancement

#49 feat/member merge
  Api/src/main/java/picasso/server/api/admin/controller/AdminController.java
  Api/src/main/java/picasso/server/api/auction/service/PictureService.java
  Api/src/main/java/picasso/server/api/exchange/controller/PaymentController.java
  Api/src/main/java/picasso/server/api/user/controller/AuthController.java
  Api/src/main/java/picasso/server/api/user/controller/MemberController.java
  Api/src/main/java/picasso/server/api/user/controller/MypageController.java
  Api/src/main/java/picasso/server/api/user/service/AuthService.java
  Api/src/main/java/picasso/server/api/user/service/AuthServiceImpl.java
  Api/src/main/java/picasso/server/api/user/service/DefaultMemberService.java
  Api/src/main/java/picasso/server/api/user/service/MypageService.java
  Api/src/main/java/picasso/server/api/user/service/UserService.java
  Api/src/main/java/picasso/server/api/user/vo/request/LoginRequestDto.java
  Api/src/main/java/picasso/server/api/user/vo/request/SignUpRequestDto.java
  Api/src/main/resources/templates/auth/form.html
  Api/src/main/resources/templates/auth/index.html
  Api/src/main/resources/templates/auth/login.html
  Api/src/main/resources/templates/auth/signup-form.html
  Api/src/main/resources/templates/fragment/header.html
  Api/src/main/resources/templates/member/detail.html
  Api/src/main/resources/templates/member/form.html
  Api/src/main/resources/templates/member/list.html
  Api/src/main/resources/templates/user/list.html
  Api/src/main/resources/templates/user/mypage.html
  Domain/src/main/java/picasso/server/domain/domains/dto/UserDTO.java
  Domain/src/main/java/picasso/server/domain/domains/member/entity/User.java
  Domain/src/main/java/picasso/server/domain/domains/member/type/UserRole.java
  Domain/src/main/java/picasso/server/domain/domains/user/entity/SocialToken.java
  Domain/src/main/java/picasso/server/domain/domains/user/entity/User.java
  Domain/src/main/java/picasso/server/domain/domains/user/repository/MypageRepository.java
  Domain/src/main/java/picasso/server/domain/domains/user/repository/UserRepository.java
  Domain/src/main/java/picasso/server/domain/domains/user/type/LoginType.java
  Domain/src/main/java/picasso/server/domain/domains/user/type/UserRole.java
  Domain/src/main/java/picasso/server/domain/domains/user/type/UserStatus.java
  Domain/src/main/resources/data.sql
  README.md
Labels: enhancement

#56 [FEATURE] 관리자 계정 생성 및 조회 구현
  Api/src/main/java/picasso/server/api/admin/controller/AdminController.java
  Api/src/main/java/picasso/server/api/admin/service/AdminService.java
  Api/src/main/java/picasso/server/api/user/vo/request/SignUpAdminRequestDto.java
  Api/src/main/resources/static/css/adminform.css
  Api/src/main/resources/static/css/adminlist.css
  Api/src/main/resources/static/css/detail.css
  Api/src/main/resources/templates/admin/detail.html
  Api/src/main/resources/templates/admin/form.html
  Api/src/main/resources/templates/admin/list.html
  Api/src/main/resources/templates/admin/memberList.html
  Domain/src/main/java/picasso/server/domain/domains/user/repository/UserRepository.java
Labels: enhancement

#66 [FEATURES] 마이 페이지 기능 구현
  Api/src/main/java/picasso/server/api/user/controller/MypageController.java
  Api/src/main/java/picasso/server/api/user/service/MypageService.java
  Api/src/main/java/picasso/server/api/user/vo/request/MyPageRequestDto.java
  Api/src/main/resources/static/css/mypage.css
  Api/src/main/resources/static/js/mypage.js
  Api/src/main/resources/templates/user/mypage.html
  Domain/src/main/java/picasso/server/domain/domains/user/entity/User.java
  Domain/src/main/java/picasso/server/domain/domains/user/repository/MypageRepository.java
Labels: enhancement
